# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: iML

# Short description (goes below the title; it will also be used in the RSS feed)
description: Introductory Machine Learning

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://ydata123.org/fa21/iml

# favicon
favicon: favicon.ico

gems:
  - jekyll-redirect-from
